### ISSUE TITLE
Usable with Salesforce SSO? Pardot Authentication retired in February 2021

### ISSUE THREAD

**Issue by luk4sschr0d3r** [bmarshall511/pardot-marketing#6]
Hi,

is this plugin usable with the Salesforce SSO authentication?

Pardot Authentication is being retired in February 2021:
https://help.salesforce.com/articleView?id=sf.pardot_connectors_wordpress_install.htm&type=5

I only see the Pardot User Email, Password, API Key settings...

Thanks,
Lukas

**Comment by bmarshall511** [comment]
No, currently not needed for what the plugin does.
